server:
  port: 8761

#  ??  ??? microservice? ?? ??
spring:
  application:
    name: discoveryservice

# ??? ???

  output:
    ansi:
      enabled: ALWAYS

# ??? true? client ??
# false? ??? server?? ???? ???? ?? ??

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

