server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: C:\webApp\msa\native-repo
        git:
          uri: https://github.com/Sirius147/spring-cloud-git.git
          default-label: master
#          uri: C:\webApp\msa\git-local-repo

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

